name: Run Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    env: # 🌍 Global env for the whole job
      VITE_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      VITE_SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      VITE_E2E: true

    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Build project for E2E
      - name: Build project for E2E
        run: npm run build:test

      # 5️⃣ Start preview server on 5173 (background)
      - name: Start server
        run: npm run preview -- --port 5173 &

      # 6️⃣ Wait for server to be ready
      - name: Wait for server
        run: npx wait-on http://localhost:5173

      # 7️⃣ Run Cypress E2E tests
      - name: Run Cypress E2E
        run: npx cypress run --e2e --browser chrome --record --key ${{ secrets.CYPRESS_RECORD_KEY }} --parallel

      # 8️⃣ Upload artifacts if tests fail
      - name: Upload Cypress screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
